language: node_js
node_js: node
cache:
  directories:
  - /home/travis/.elm
  - node_modules
  - elm-stuff
install:
- npm install -g elm@0.19.0 elm-test@0.19.0-beta4
script:
- elm-test
notifications:
  email:
    recipients:
    - unsoundscapes@gmail.com
